# Generated by Django 5.2.14 on 2026-05-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_user_id_0ae59f_idx',
            old_name='orders_user_created_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_status_079368_idx',
            old_name='orders_status_created_idx',
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
