[pytest]
DJANGO_SETTINGS_MODULE = core.settings.test
python_files = tests.py test_*.py *_tests.py
addopts = -ra --strict-markers
markers =
    slow: marks tests as slow
    integration: requires Postgres + Redis
    benchmark: pytest-benchmark cases
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
