# Generated by Django 5.2.14 on 2026-05-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='catalog_pro_categor_891fe8_idx',
            old_name='catalog_pro_cat_act_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='catalog_pro_price_2d2a4c_idx',
            old_name='catalog_pro_price_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='catalog_pro_created_eee82f_idx',
            old_name='catalog_pro_created_idx',
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
